version: "3.8"
services:
  firebase_emulator:
    container_name: firebase_emulator
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    tty: true
    ports:
      - "5001:5001"
      - "9000:9000"
      - "8080:8080"
      - "5000:5000"
